version: '3.1'

name: argon-dev

services:
  mongo:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - ./replica.key:/data/replica.key
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: test
      MONGO_REPLICA_SET_NAME: rs0
      MONGO_SHARDING_ENABLED: false
    command: mongod --replSet rs0 --bind_ip_all --keyFile /data/replica.key

  minio:
    image: minio/minio
    restart: always
    ports:
      - 9000:9000
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: server /data

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=password

volumes:
  mongodb:
  minio:
  redis:
  rabbitmq: