version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    volumes:
      - argon-mongo:/data/db
      - ./keyfile:/data/keyfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: test
      MONGO_REPLICA_SET_NAME: rs0
      MONGO_SHARDING_ENABLED: false
    command: mongod --replSet rs0 --bind_ip_all --keyFile /data/keyfile

  minio:
    image: minio/minio
    restart: always
    ports:
      - 9000:9000
    volumes:
      - argon-minio:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: server /data

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

volumes:
  argon-mongo:
  argon-minio:
