version: '3.1'

name: argon-dev

services:
  mongo:
    image: bitnami/mongodb
    restart: always
    ports: 
      - 27017:27017
    volumes:
      - mongodb:/bitnami/mongodb
    environment:
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: password
      MONGODB_DATABASE: test
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: ThisIsAUniqueKeyThatShouldBeChanged123

  minio:
    image: minio/minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    restart: always
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=password

volumes:
  mongodb:
  minio:
  redis:
  rabbitmq: